Channel recovery
AutoResearch/EEG-GAN pull request #108
Opened 2024-07-23 19:22 UTC by TheLemonPig

Channel Recovery training:
1. Adding a `recover_channels` parameter to the autoencoder training
2. Adding a `recover_channels` parameter to the gan training
3. Train AE and GAN with this same parameter adjustment

2024-07-23 19:39 UTC, TheLemonPig commented
Is there some way to check the Autoencoder's configuration while you are inside the GAN training? The only reason to add any mention of channel recovery in the GAN training is just to make sure that the user knows that the AE they are using was trained to recover channels (i.e. to make sure they choose the right AE for their GAN training)

2024-07-24 15:35 UTC, chadcwilliams requested changes
I am delaying the PR for two reasons. 

1. The dev branch is currently EEG-GAN v2.0 as will be deployed, so at this point it should not be modified. I will work on deploying it soon so that the dev branch is again open for changes. 

2. You mentioned in slack that these changes are not yet tested. I believe it would be best to ensure that this works on your branch before we merge into the code. This would include making sure that all past functionality still works (i.e., your changes did not effect the package when not doing channel recovery).

2024-07-24 17:36 UTC, TheLemonPig commented
Hi @chadcwilliams sounds good. I completely understand. I wanted to create this as a draft PR so that you guys could see the work as it was being done. I wouldn't want to make it a proper PR until I can confirm it works. I think that is a great idea to also make sure that all previous functionality is not broken by the added features.

2025-06-24 18:43 UTC, chadcwilliams commented
Closing as there has not been any progress on this for a long time.

2025-06-24 18:43 UTC, closed without merging